<?php
namespace chipbug\addbulkusers;

/*
Plugin name: cb add multiple users
Description: allows multiple users to be generated by simply adding a list of names separated by a comma.
Author: PC
Author URI: https://chipbug.com
Version: 1.0.0
*/

defined('ABSPATH') or exit;

require_once 'class-admin-install.php';
require_once 'class-admin-setup.php';
require_once 'class-admin-operations.php';

if (is_admin()) {
    //new Admin_Install();
    new Admin_Setup();
    new Admin_Operations();
}
